apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-app
  template:
    metadata:
      labels:
        app: github-app
    spec:
      containers:
      - name: github-app
        image: zakyaakram/github-app:latest
        ports:
        - containerPort: 8080
