name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: github-app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # 1. Checkout
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Java (عشان Maven)
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Run Unit Tests
    - name: Run Unit Tests
      run: mvn test

    # 4. Build App
    - name: Build Application
      run: mvn clean package -DskipTests

    # 5. Build Docker Image
    - name: Build Image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest .

    # 6. Scan Image (Trivy)
    - name: Scan Image
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        aquasec/trivy image ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest || true

    # 7. Login to DockerHub
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    # 8. Push Image
    - name: Push Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest

    # 9. Remove Local Image
    - name: Remove Local Image
      run: |
        docker rmi ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest || true

    # 10. Setup kubectl
    - name: Setup Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yam
